import React from 'react';
import axios from 'axios';

export default class ResidentAsessment extends React.Component {
  state = {
    assessmentDate:'',
    assessorFirstName:'',
    assessorLastName:'',
    assessorSignature:'',
    residentMaritalStatus:'',
    residentLanguage:'',
    residentLivingArrangement:'',
    residentAddressStreet:'',
    residentAddressCity:'',
    residentAddressProv:'',
    residentAddressPostCode:'',
    residentCurrentLocation:'',
    residentMedicallyStable:'',
    residentMentalStatus:'',
    residentOrientedPerson:'',
    residentOrientedPlace:'',
    residentOrientedTime:'',
    residentOrientedOccConfused:'',
    residentPOA:'',
    medicalConditions:'',
    currentMedication:'',
    alergies:'',
    familyDoctor:'',
    familyDoctorPhone:'',
    familyDoctorEmail:'',
    hobbiesAndSpecialInterests:'',
    eating:'',
    eatingNotes:'',
    transfer:'',
    transferNotes:'',
    mobilityWalking:'',
    mobilityWalkingNotes:'',
    mobilityWheelChair:'',
    mobilityWheelChairNotes:'',
    toileting:'',
    toiletingNotes:'',
    bathing:'',
    bathingNotes:'',
    hygiene:'',
    hygieneNotes:'',
    dressing:'',
    dressingNotes:'',
    orientationDementia:'',
    orientationDementiaNotes:'',
    communicationExpressive:'',
    communicationExpressiveNotes:'',
    communicationReceptive:'',
    communicationReceptiveNotes:'',
    medicationSelfAdmin:'',
    medicationSelfAdminNotes:'',
    behaviours:'',
    behavioursNotes:'',
    mentalHealthSubstanceAbuse:'',
    mentalHealthSubstanceAbuseNotes:'',
    hearing:'',
    hearingNotes:'',
    oralAndVisionCare:'',
    oralAndVisionCareNotes:'',
    socialSupport:'',
    socialSupportNotes:'',
    assessmentValue:'',
    assessmentValuePercent:'',
    skilledNursingServicesPressureUlcer:'',
    skilledNursingServicesIVHyperal:'',
    applicantAdheresToMedicalCare:'',
    assessmentSummary:''
    }

  handleChange = event => {
    this.setState({ 
    assessmentDate: event.target.value,
    assessorFirstName: event.target.value,
    assessorLastName:event.target.value,
    assessorSignature: event.target.value,
    residentMaritalStatus: event.target.value,
    residentLanguage: event.target.value,
    residentLivingArrangement: event.target.value,
    residentAddressStreet: event.target.value,
    residentAddressCity: event.target.value,
    residentAddressProv: event.target.value,
    residentAddressPostCode: event.target.value,
    residentCurrentLocation: event.target.value,
    residentMedicallyStable: event.target.value,
    residentMentalStatus: event.target.value,
    residentOrientedPerson:event.target.value,
    residentOrientedPlace:event.target.value,
    residentOrientedTime:event.target.value,
    residentOrientedOccConfused:event.target.value,
    residentPOA: event.target.value,
    medicalConditions: event.target.value,
    currentMedication: event.target.value,
    alergies: event.target.value,
    familyDoctor: event.target.value,
    residentPhone: event.target.value,
    residentEmail: event.target.value,
    hobbiesAndSpecialInterests: event.target.value,
    eating: event.target.value,
    eatingNotes: event.target.value,
    transfer: event.target.value,
    transferNotes: event.target.value,
    mobilityWalking: event.target.value,
    mobilityWalkingNotes: event.target.value,
    mobilityWheelChair: event.target.value,
    mobilityWheelChairNotes: event.target.value,
    toileting: event.target.value,
    toiletingNotes: event.target.value,
    bathing: event.target.value,
    bathingNotes: event.target.value,
    hygiene: event.target.value,
    hygieneNotes: event.target.value,
    dressing: event.target.value,
    dressingNotes: event.target.value,
    orientationDementia: event.target.value,
    orientationDementiaNotes: event.target.value,
    communicationExpressive: event.target.value,
    communicationExpressiveNotes: event.target.value,
    communicationReceptive: event.target.value,
    communicationReceptiveNotes: event.target.value,
    medicationSelfAdmin: event.target.value,
    medicationSelfAdminNotes: event.target.value,
    behaviours: event.target.value,
    behavioursNotes: event.target.value,
    mentalHealthSubstanceAbuse: event.target.value,
    mentalHealthSubstanceAbuseNotes: event.target.value,
    hearing: event.target.value,
    hearingNotes: event.target.value,
    oralAndVisionCare: event.target.value,
    oralAndVisionCareNotes: event.target.value,
    socialSupport: event.target.value,
    socialSupportNotes: event.target.value,
    assessmentValue: event.target.value,
    assessmentValuePercent: event.target.value,
    skilledNursingServicesPressureUlcer: event.target.value,
    skilledNursingServicesIVHyperal: event.target.value,
    applicantAdheresToMedicalCare: event.target.value,
    assessmentSummary: event.target.value
    });
    
  }

  handleSubmit = event => {
    event.preventDefault();

    const assessment = {
    assessmentDate: this.state.assessmentSummary,
    assessorFirstName: this.state.assessorFirstName,
    assessorLastName: this.state.assessorLastName,
    assessorSignature: this.state.assessorSignature,
    residentMaritalStatus: this.state.residentMaritalStatus,
    residentLanguage: this.state.residentLanguage,
    residentLivingArrangement: this.state.residentLivingArrangement,
    residentAddressStreet: this.state.residentAddressStreet,
    residentAddressCity: this.state.residentAddressCity,
    residentAddressProv: this.state.residentAddressProv,
    residentAddressPostCode: this.state.residentAddressPostCode,
    residentCurrentLocation: this.state.residentCurrentLocation,
    residentMedicallyStable: this.state.residentMedicallyStable,
    residentMentalStatus: this.state.residentMentalStatus,
    residentOrientedPerson:this.state.residentOrientedPerson,
    residentOrientedPlace:this.state.residentOrientedPlace,
    residentOrientedTime:this.state.residentOrientedTime,
    residentOrientedOccConfused:this.state.residentOrientedOccConfused,
    residentPOA: this.state.residentPOA,
    medicalConditions: this.state.medicalConditions,
    currentMedication: this.state.currentMedication,
    alergies: this.state.allergies, 
    familyDoctor: this.state.familyDoctor,
    residentPhone: this.state.residentPhone,
    residentEmail: this.state.residentEmail,
    hobbiesAndSpecialInterests: this.state.hobbiesAndSpecialInterests,
    eating: this.state.eating, 
    eatingNotes: this.state.eatingNotes,
    transfer: this.state.transfer, 
    transferNotes: this.state.transferNotes,
    mobilityWalking: this.state.mobilityWalking,
    mobilityWalkingNotes: this.state.mobilityWalkingNotes,
    mobilityWheelChair: this.state.mobilityWheelChair,
    mobilityWheelChairNotes: this.state.mobilityWheelChairNotes,
    toileting: this.state.toileting, 
    toiletingNotes: this.state.toiletingNotes,
    bathing: this.state.bathing, 
    bathingNotes: this.state.bathingNotes,
    hygiene: this.state.hygiene,
    hygieneNotes: this.state.hygieneNotes,
    dressing: this.state.dressing, 
    dressingNotes: this.state.dressingNotes,
    orientationDementia: this.state.orientationDementia,
    orientationDementiaNotes: this.state.orientationDementiaNotes,
    communicationExpressive: this.state.communicationExpressive,
    communicationExpressiveNotes: this.state.communicationExpressiveNotes,
    communicationReceptive: this.state.communicationReceptive, 
    communicationReceptiveNotes: this.state.communicationReceptiveNotes,
    medicationSelfAdmin: this.state.medicationSelfAdmin,
    medicationSelfAdminNotes: this.state.medicationSelfAdminNotes,
    behaviours: this.state.behaviours,
    behavioursNotes: this.state.behavioursNotes,
    mentalHealthSubstanceAbuse: this.state.mentalHealthSubstanceAbuse,
    mentalHealthSubstanceAbuseNotes: this.state.mentalHealthSubstanceAbuseNotes,
    hearing: this.state.hearing, 
    hearingNotes: this.state.hearingNotes,
    oralAndVisionCare: this.state.oralAndVisionCare,
    oralAndVisionCareNotes: this.state.oralAndVisionCareNotes,
    socialSupport: this.state.socialSupport, 
    socialSupportNotes: this.state.socialSupportNotes,
    assessmentValue: this.state.assessmentValue,
    assessmentValuePercent: this.state.assessmentValuePercent,
    skilledNursingServicesPressureUlcer: this.state.skilledNursingServices,
    skilledNursingSercicesIVHyperal: this.state.skilledNursingServicesIVHyperal,
    applicantAdheresToMedicalCare: this.state.applicantAdheresToMedicalCare,
    assessmentSummary: this.state.assessmentSummary
    };

    axios.post(`http://localhost:4001/api/assessmentsadd`, { assessment })
      .then(res => {
        console.log(res);
        console.log(res.data);
      })
  }

  render() {
    return (
      <div>
        <form onSubmit={this.handleSubmit}>
          <label>
            Person Name:
            <input type="text" name="name" onChange={this.handleChange} />
          </label>
          <button type="submit">Add</button>
        </form>
      </div>
    )
  }
}